
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { LanguageProvider } from "@/context/LanguageContext";
import { getServerLanguage } from "@/lib/server-cookies";

import { Work_Sans, Tajawal } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";

const work_sans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const tajawal = Tajawal({
  subsets: ["latin"],
  variable: "--font-tajawal",
  weight: ["200", "300", "400", "500", "700", "800", "900"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialLanguage = await getServerLanguage();

  return (
    <html lang="en">
      <body
        className={`${work_sans.variable} ${tajawal.variable} antialiased`}
      >
        <LanguageProvider initialLanguage={initialLanguage}>
          <ThemeProvider defaultTheme="light">
            <AuthProvider >
              {children}
            </AuthProvider>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
